version: 2
updates:
  - package-ecosystem: nuget
    directory: /src
    schedule:
      interval: quarterly
    labels:
      - dependencies
    cooldown:
      default-days: 10
      semver-major-days: 60
      semver-minor-days: 14
      semver-patch-days: 7
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: quarterly
    groups:
      docker-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: deps(docker)
